import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/providers";
import localFont from "next/font/local";

const tajawal = localFont({
  src: "./fonts/Tajawal-Regular.ttf",
  variable: "--font-tajawal",
});

export const metadata: Metadata = {
  title: "Ms Dirbal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${tajawal.variable} font-sans antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
